version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9200:9200"
    volumes:
      - ./assets:/app/assets
    env_file:
      - .env
    environment:
      - PORT=9200
      - DEBUG=false
    restart: unless-stopped 